### ISSUE TITLE
Brazil regions for populationData.tsv

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#345]
We have the country Brazil now, but the smaller divisions are missing. We have case data for them already. Maybe @gstvribs can help?

**Comment by nnoll** [comment]
@gstvribs have you had any luck tracking down this data?

**Comment by gstvribs** [comment]
Yes, some work but still in WIP help wanted please : )

I invited a [github org](https://github.com/covid-taskforce-cplp) that i participate to help me in this issue

**Comment by pauloangelo** [comment]
Hi all,

"BRA-Distrito Federal" is outdated. Who is updating?  I'm willing to help if needed.

Regards,

Paulo Angelo

**Comment by nnoll** [comment]
Hey Paulo,

It would be great if you could submit updated data for any/all Brazilian regions. If you supply population statistics, we can provide generated presets for them.

**Comment by pauloangelo** [comment]
> Hey Paulo,
> 
> It would be great if you could submit updated data for any/all Brazilian regions. If you supply population statistics, we can provide generated presets for them.

Hi @nnoll ,

The data from the Brazilian regions are available at [1]. Covid-19 Scenarios already has scripts to retrieve and parse this data. I shared at [2] the presets for the region "BRA-Distrito Federal". 

The populations' sizes can be found in our last census (2010). The population by age are in table [3] for each region.

regards,

Paulo Angelo

[1] https://brasil.io/covid19/
[2] https://github.com/neherlab/covid19_scenarios/issues/69#issuecomment-636390682 
[3] ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Sinopse/Brasil/sinopse_brasil_tab_1_12.zip

**Comment by pauloangelo** [comment]
> Hi all,
> 
> "BRA-Distrito Federal" is outdated. Who is updating? I'm willing to help if needed.
> 
> Regards,
> 
> Paulo Angelo

Hi all,

The data of region "BRA-Distrito Federal" is outdated. The last available day in Covid-19 Scenarios is 2020-06-26.

Thx in advance.

regards,

Paulo Angelo

**Comment by pauloangelo** [comment]
:worried:

**Comment by ivan-aksamentov** [comment]
Hey @pauloangelo , sorry for the delay.

The problem was that our source have changed the URL and file format. I fixed that in #760  and just let @rneher to take another look and merge.

**Comment by rneher** [comment]
This is now released. We still don't have have the population data for Brazilian regions, but the case counts are updated and will be updated every few days going forward.
